### ISSUE TITLE
Request: Option to download the raw pack rather than an installer

### ISSUE THREAD

**Issue by jc2xs** [CreeperHost/modpacksch-serverdownloader#16]
I run a Linux server using AMP.  AMP has everything built in to select and setup minecraft servers (vanilla, fabric, forge, etc.).  Normally, I just use the AMP interface to setup the minecraft and forge versions required and then just copy up the mods, config and other pack folders needed.

With the current process, I'm now forced to download an installer instead.  Would there be any way to just specify a pack download for servers similar to what I've used in the past on CurseForge?

**Comment by ThePaul-T** [comment]
Unfortunately not. A lot of this is designed around cost-effectiveness and validation.

Most CDN's have a per-file limit unless you pay considerably higher fees; modern modpacks are above that limit now, we designed the system around individual files being downloaded one at a time, this means until the point a single mod is 250mb, all files are cached and served locally to the server/user.

The second part of this, is it allows per file validation at download, with retries, so those with less stable connections only need to redownload the individual damaged files, also allows us to create validation systems, and download the required JRE's as it is now a case of ensuring you have the correct JRE for your MC version.

All in all, AMP should be able to run a script; if it can run a script, it can run the server downloader. You do not need to download a new server downloader each time, you can rename the file or use the --latest argument.

I understand your reason for wanting the zips, but they were considered, and this approach has substantially more benefits than drawbacks.

Change is scary, but this helps us make things better for everyone.
