### ISSUE TITLE
Serverinstall.exe for Windows fails to load all files. 

### ISSUE THREAD

**Issue by Fade-Alchemist** [CreeperHost/modpacksch-serverdownloader#17]
Every update, I need to run the new Serverinstall.exe multiple times hoping that one of them will include all files - it's like rolling dice. 

![Untitled](https://user-images.githubusercontent.com/29619427/217713700-d362a808-71ea-49b2-bc01-9c5e52d2d8ac.png)

Yes, I am using the most up-to-date installer, and no, it is not running out of a cloud-based folder. I have attached a copy of the .exe I am using. 

[serverinstall_100_2328.zip](https://github.com/CreeperHost/modpacksch-serverdownloader/files/10693331/serverinstall_100_2328.zip)

**Comment by Fade-Alchemist** [comment]
After 10 tries (TEN!) I was able to get all the files but one - after scrubbing through the command prompt I found this:

Error downloading https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.2%2B8/OpenJDK17U-jdk_x64_windows_hotspot_17.0.2_8.zip: Get "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.2%2B8/OpenJDK17U-jdk_x64_windows_hotspot_17.0.2_8.zip": dial tcp: lookup github.com: no such host

I don't know what any of that means. But perhaps that is part of the problem. This is either gibberish or it helps, thought i might as well post what I found here.

**Comment by ThePaul-T** [comment]
Well the specific error there is that your own PC can't resolve github.com, so that isn't really something we can fix, you have intermittent DNS resolution issues on your PC.
