### ISSUE TITLE
Folder or version.json gets wrong permission after installing ModPack

### ISSUE THREAD

**Issue by runih** [CreeperHost/modpacksch-serverdownloader#4]
When using `serverinstall_80_225` to install the Endeavour modpack and install it in the current folder. The `version.json` will get the wrong permission: `--w----r--`, which means  that the owner doesn't have permission to read the file.

If you instead enter a folder name to install the modpack, the folder will get the wrong permission: `d-wxr----x` which also means that the owner doesn't have read access to the folder.

**Comment by ThePaul-T** [comment]
We use this installer extensively (500+ times a day minimum) and have seen no such issues. Please include the installer version, OS version and other useful information we can use to reproduce this issue.

**Comment by runih** [comment]
I don't know how you get the version number out of `serverintall_80_225` I though you could see that by the name... but this is the sha of the binary if that helps: `54ee713ed4c9712ae8b74936acdaef0eb752e744`.
You may be right that you have run it 500+ times a day... I've run it about 10 times on Linux and twice on  a Mac... and it give the same result each time! I'm just reporting what I'm seeing.

This is the linux version:
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

This is the MacOs Version:
```
  Systemversion:	macOS 11.2.3 (20D91)
  Kärnversion:	Darwin 20.3.0
```

**Comment by ThePaul-T** [comment]
Thanks, we'll create a VM and recreate the issue then try fixes.

If you run it with --help, it should print out usage, version and other information.

**Comment by runih** [comment]
build 202122021721

**Comment by jikuja** [comment]
Reproducible in my mac also.

Looks like https://github.com/CreeperHost/modpacksch-serverdownloader/blob/golang/modpacksch.go#L176 and https://github.com/CreeperHost/modpacksch-serverdownloader/blob/golang/main.go#L210 have missing leading zero in the permission parameter.
